### ISSUE TITLE
SCSS issues in umbraco area

### ISSUE THREAD

**Issue by avialonn** [jaandrews/customPicker#1]
Hi and many thanks for this cool package.
The > sign in the styles.scss is transformed into &gt which cause issues in the smidge  (runtime minification)

`  &.disabled {
            > .icon, a {
                opacity: .7;
            }
        }
`
I tried to fix the scss but it automatically regenerate the whole appplugin folder upon build.
Any idea on how to solve this?
Thanks!
aa

**Comment by jaandrews** [comment]
@avialonn The package manifest for this package references the [css file](https://github.com/jaandrews/customPicker/blob/v10/main/Bonsai.CustomPicker.Backoffice/App_Plugins/CustomPicker/style.css), so fixing the file there should fix it. If you aren't seeing that change reflected in the backoffice, try setting a [runtime minification version](https://docs.umbraco.com/umbraco-cms/reference/configuration/runtimeminificationsettings) in appsettings.json to force umbraco to generate a fresh bundle. I'll aim to have a fix for this issue deployed to nuget sometime this week.

**Comment by avialonn** [comment]
Thanks @jaandrews.
The issue is that everytime i change this file it get regenerated. 
Actually the whole app_plugin folder for your project is regenerated. Is it something on your side?
Thanks

**Comment by jaandrews** [comment]
@avialonn It's likely due to some [project configuration](https://github.com/jaandrews/customPicker/blob/v10/main/Bonsai.CustomPicker.Backoffice/Bonsai.CustomPicker.Backoffice.csproj#L33) I have to ensure the files are deployed. Umbraco 9+ causes [some issues](https://github.com/umbraco/Umbraco-CMS/issues/12572) for projects that rely on files in the app_plugins folder out of the box and that configuration is one of the workarounds.

**Comment by jaandrews** [comment]
@avialonn That typo has been corrected in the 1.0.2 release.
